### PR TITLE
Rename start.cmd to start.bat

### PR DESCRIPTION
**Pull request by Dog2puppy**
1. Its for windows, so start.bat
2. Why is there Genisys stuff here? Server status system?

### CODE REVIEW

**Comment by AmiroEmad** [comment]
i used genysis console system lol

**Comment by Dog2puppy** [comment]
XD

**Comment by AmiroEmad** [comment]
let me test

**Comment by AmiroEmad** [comment]
why did you delete i didn't test it as i cant test until i merge

**Comment by Dog2puppy** [comment]
Reopened. But it wont work. I thought windows didn't accept .cmd

**Comment by Dog2puppy** [comment]
But I guess it does

**Comment by AmiroEmad** [comment]
i tested it before upload the issue i am having is with the signature of the start.cmd

**Comment by AmiroEmad** [comment]
Start.bat wont work sorry

**Pull request closed without merging**
